# 参考： https://ffis.me/archives/2213.html
kind: pipeline
name: default

#workspace:
# 公共区域
#  base: /step-common-disk
# git clone 位置
#  path: /test

clone:
  # 拉代码，只拉最新，不需要下载 commit 历史记录，加快速度
  disable: false
  depth: 1

steps:
  - name: 编译、打包、发布到 maven 仓库
    image: cnlym/maven:3-jdk-21-alpine-aliyun
    # 加速，对于这种稳定的容器
    pull: if-not-exists
    volumes:
      - name: mvnCache
        path: /root/.m2
    commands:
      # 异步快速检查依赖
      - curl --location --request POST 'http://autopom.itlym.cn:12345/projects/create' --form 'email=cn_lym@foxmail.com' --form 'pomXml=@shoulder-dependencies/pom.xml' --form 'notifyInstantlyAfterCheck=true' --form 'notifyReason=CI-<a href="https://git.itlym.cn/gogs/${DRONE_REPO_NAME}">${DRONE_REPO_NAME}::${DRONE_REPO_BRANCH}</a><br> with <a href="https://drone.itlym.cn/gogs/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}">Drone Build-${DRONE_BUILD_NUMBER}</a><br>' || echo '======= SKIP dependency check. ======='
      #
      - export MAVEN_OPTS="-Xmx400m -Xms400m"
      # ========== 安装到本地 install script ==========
      #- mvn clean install -P release -Dmaven.test.skip=true -B -V -T 1.5C
      # ========== install script end ==========
      #
      # ========== deploy script ==========
      - bash scripts/prepareRelease.sh
      - mvn clean deploy -XP release -Dmaven.test.skip=true -B -V -T 1.5C
      # ========== deploy script end ==========
      - echo '========FINISHED CICD=========='

  - name: 构建结果通知 Build Notification. --- with DingTalk
    image: guoxudongdocker/drone-dingtalk
    # 加速，对于这种稳定的容器
    pull: if-not-exists
    settings:
      token:
        from_secret: ding_token
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      # CANLCEL 不通知
      status: [failure, success]

volumes:
  - name: mvnCache
    host:
      path: /tmp/cache/.m2

trigger:
  branch:
    - master
  event:
    - push
