demo:
  auth:
    host: authServer.com
    port: 8081
    uri: http://${demo.auth.host:localhost}:${demo.auth.port:8081}
  resource:
    host: resourceServer.com
    port: 8000
    uri: http://${demo.resource.host:localhost}:${demo.resource.port:8000}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR}/demo_shoulder?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ${MYSQL_PWD} # 这里使用了系统的环境变量，参见 spring boot 的特性

shoulder:
  application:
    errorCodePrefix: '0x000b'
  web:
    handleGlobalException: false
  # ---------------------------- 关注这里 ------------------------------
  security:
    auth: # 如果使用者自行实现登录成功、退出成功处理器，则这些配置将失效，使用者实现的优先生效
      type: token # 测试环境这里设置为 token。session 方式已经在页面上可以测过了！！！！！！！
      responseType: json