spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR}/demo_shoulder?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ${MYSQL_PWD} # 这里使用了系统的环境变量，参见 spring boot 的特性

  profiles:
    active: session

shoulder:
  application:
    errorCodePrefix: '0x000b'