spring:
  application:
    name: ${appId}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDR}/yourDataBaseName?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: ${MYSQL_PWD}

shoulder:
  application:
    id: ${spring.application.name}
    errorCodePrefix: '0x000b' # unique code to mark a application
