# demo2 使用 yaml 格式配置作为示例，properties转yaml: https://www.toyaml.com/index.html
REDIS_ADDR: itlym.cn
MYSQL_ADDR: itlym.cn
MYSQL_PWD: mysqlrootpwd!
REDIS_PWD: redisssss
spring:
  application:
    name: demo2

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 不应使用 UTC 时间，因为 LocalDateTime 带时区，所以最好和系统保持一致 Asia/Shanghai、SQL show variables like '%time_zone%';
    url: jdbc:mysql://${MYSQL_ADDR}/shoulder_platform?serverTimezone=Asia/Shanghai&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: ${MYSQL_PWD} # 这里使用了系统的环境变量，参见 spring boot 的特性

shoulder:
  application:
    errorCodePrefix: '0x000b'
    id: ${spring.application.name}


  log:
    operation:
      logger:
        type: jdbc

logging:
  level:
    org:
      springframework: warn

debug: false